/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'szpak' at '8/7/14 1:02 PM' with Gradle 2.0
 *
 * @author szpak, @date 8/7/14 1:02 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
