/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'szpak' at '8/7/14 1:02 PM' with Gradle 2.0
 *
 * @author szpak, @date 8/7/14 1:02 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
