/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'szpak' at '12/2/14 12:27 PM' with Gradle 2.2
 *
 * @author szpak, @date 12/2/14 12:27 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
