/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multi.pit;

public class App {
    public String getGreeting(boolean whichOne) {
        return whichOne ? "Hello world." : "Witaj świecie.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting(true));
    }
}
