/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Groovy project to get you started.
 * For more details take a look at the Groovy Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.5/userguide/tutorial_groovy_projects.html
 */

plugins {
    // Apply the groovy plugin to add support for Groovy
    groovy

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    mavenCentral()
    maven { url = uri("https://oss.jfrog.org/artifactory/oss-snapshot-local/") }
}

dependencies {
    // Use the latest Groovy version for building this library
//    implementation("org.codehaus.groovy:groovy:3.0.4")
    implementation("org.apache.groovy:groovy:4.0.0-SNAPSHOT")

    // Use the awesome Spock testing and specification framework
    testImplementation("org.spockframework:spock-core:2.0-M3-groovy-3.0") {
        exclude(group = "org.codehaus.groovy")
    }
}

tasks {
    withType<Test>().configureEach {
        useJUnitPlatform()
    }

}

