/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'szpak' at '12/2/14 12:27 PM' with Gradle 2.2
 *
 * @author szpak, @date 12/2/14 12:27 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
