/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multi.pit;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.getGreeting(true), "Hello world.");
    }
    @Test void appHasAGreeting2() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(false), "Witaj świecie.");
    }
}
